### ISSUE TITLE
Move Existing Install

### ISSUE THREAD

**Issue by MayaSima** [portapps/signal-portable#25]
### Behaviour
As per: https://portapps.io/app/signal-portable/#modifications

If you have already installed Signal from the original setup, move the following files :

%APPDATA%\Signal\* to data
Then run signal-portable.exe and [remove](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98) Signal from your computer.

#### Steps to reproduce this issue

1. move %APPDATA%\Signal\* to data
2. run signal-portable.exe

#### Expected behaviour

Proper running of Signal

#### Actual behaviour

Database startup error:

Error: Error: SQL: User version is 58 but the expected maximum version is 54. Did you try to start an old version of Signal?
    at updateSchema ([REDACTED]\ts\sql\migrations\index.js:1590:11)
    at Object.initialize ([REDACTED]\ts\sql\Server.js:354:40)
    at MessagePort.<anonymous> ([REDACTED]\ts\sql\mainWorker.js:68:35)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.<anonymous> ([REDACTED]\ts\sql\main.js:55:26)
    at Worker.emit (node:events:390:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

When closing the error another one gets generated:

Unhandled Promise Rejection

Error: Not initialized
    at MainSQL.close ([REDACTED]\ts\sql\main.js:90:13)
    at BrowserWindow.<anonymous> ([REDACTED]\app\main.js:443:15)

When closing this error a final error states:

Command Failed

### Configuration

**App release:

5.38.0-7

**Operating system:

Windows 10 Ent 64 bits

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/13040479/172043678-a322cebb-be6a-4780-9cb9-e093c549b2b8.png)

### Screenshots

![image](https://user-images.githubusercontent.com/13040479/172043696-5a9b7bac-bc5d-4272-8650-bd4a3ab6af17.png)
![image](https://user-images.githubusercontent.com/13040479/172043712-ffe72ec4-cbca-4052-89f0-3d40c82e433c.png)
![image](https://user-images.githubusercontent.com/13040479/172043728-d6da010d-a301-4f3f-9951-4ed37b657912.png)

### Logs

[signal-portable.log](https://github.com/portapps/signal-portable/files/8839663/signal-portable.log)

**Comment by dasgewirrkai** [comment]
the app works perfectly, but when I take it to another PC, it asks me to “delete and restart”. That is, it erases all the data.
